name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          cache: true
          cache-dependency-path: packages.lock.json   
          
      - name: Restore
        run: dotnet restore GeoProfiles.sln
      
      - name: Build (warnings → errors)
        run: dotnet build GeoProfiles.sln --configuration Release -warnaserror

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      
      - name: Install JS deps
        run: npm ci
      
      - name: Run Jest integration tests
        run: npm test
