name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore GeoProfiles.sln

      - name: Build
        run: dotnet build GeoProfiles.sln --configuration Release -warnaserror
        
      - name: Install dotnet-ef
        run: dotnet tool install --global dotnet-ef --version 8.0.0
        
      - name: Run infra script
        run: |
              chmod +x scripts/run-infra.sh
              scripts/run-infra.sh

      - name: Wait for API
        run: |
          for i in {1..60}; do
            code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/healthz || true)
            [ "$code" = "200" ] && exit 0
            sleep 1
          done
          echo "API did not become healthy" && exit 1

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install JS deps
        run: npm ci

      - name: Run Jest integration tests
        run: npm test

      - name: Down containers
        if: always()
        run: docker compose down -v
